### ISSUE TITLE
RAC podspec has duplicated data

### ISSUE THREAD

**Issue by ashfurrow** [mhuusko5/Podspecs#7]
We should reduce duplication for UI-specific things. See conversation at https://github.com/mhuusko5/Podspecs/pull/6/files#discussion_r51439737

Luckily, since podspecs are Ruby, this should be easy.

**Comment by NachoSoto** [comment]
Oooh I actually meant 4 places, counting the Podspec as just 1 (Xcode is to blame for the other 3). I see that there's also duplication within the Podspec :+1:

**Comment by ashfurrow** [comment]
I think RxSwift and Moya use the podspec to generate the Carthage Xcode project, but I reckon you've already thought of that solution.

**Comment by orta** [comment]
Realistically speaking, you can't really reduce this podspec's duplication without probably too much abstraction, making it harder to maintain, it's probably not worth doing this issue.

**Comment by NachoSoto** [comment]
Yeah FWIW I was mostly complaining about the fact that Xcode requires this to be in 3 places, which isn't really actionable.

**Comment by ashfurrow** [comment]
Coooooooool.

**Comment by orta** [comment]
I thought about that a little bit, in theory each file could have a notation of what OS' it supported - then every reference would just contain all of them. 

Other than that, our best attempts would be to go work for Apple :P
